version: '3'
services:
  receiver:
    build: ./receiver
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
      - ./userbot_media:/app/userbot_media
    ports:
      - "${PUBLIC_MEDIA_PORT:-8181}:${PUBLIC_MEDIA_PORT:-8181}"
  sender:
    build: ./sender
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
    ports:
      - "8001:8001"
